version: "3.8"
services:
  database:
    container_name: postgres
    image: postgres:alpine
    expose:
      - "5432"
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - "dbdata:/var/lib/postgresql/data"
  webapp:
    container_name: webapp
    image: florianvd/mirror-of-erised:webapp-latest
    depends_on:
      - database
    ports:
      - "80:80"
    environment:
      SENDGRID: ${SENDGRID_KEY}
      CLIENTID: ${CLIENT_ID}
      CLIENTSECRET: ${CLIENT_SECRET}
  api:
    container_name: api
    image: florianvd/mirror-of-erised:api-latest
    depends_on:
      - database
    ports:
      - "5000:80"
    environment:
      SENDGRID: ${SENDGRID_KEY}
      CLIENTID: ${CLIENT_ID}
      CLIENTSECRET: ${CLIENT_SECRET}
volumes:
  dbdata:
