version: "3.8"
services:
  database:
    container_name: postgres
    image: postgres:alpine
    expose:
      - "5432"
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - "dbdata:/var/lib/postgresql/data"
  webapp:
    container_name: webapp
    image: webapp:latest
    depends_on:
      - database
    ports:
      - "443:443" 
      - "80:80"
    environment:
      SENDGRID: # Sendgrid key
      CLIENTID: # Google client id
      CLIENTSECRET: # Google client secret
  api:
    container_name: api
    image: api:latest
    depends_on:
      - database
    ports:
      - "5001:443"
      - "5000:80"
    environment:
      SENDGRID: # Sendgrid key
      CLIENTID: # Google client id
      CLIENTSECRET: # Google client secret
volumes:
  dbdata:
