version: "3.8"
services:
  database:
    container_name: postgres
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - "dbdata:/var/lib/postgresql/data"
volumes:
  dbdata:
