version: "3.6"
services:
  database:
    container_name: postgres
    image: postgres:alpine
    expose:
      - "5432"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - "dbdata:/var/lib/postgresql/data"
  webapp:
    container_name: webapp
    image: florianvd/mirror-of-erised:webapp-x86
    depends_on:
      - database
    ports:
      - "80:80"
    environment:
      CONTAINERIZED: 'true'
      Authentication:Google:ClientId: ${GOOGLE_CLIENT_ID}
      Authentication:Google:ClientSecret: ${GOOGLE_CLIENT_SECRET}
    volumes:
      - ./backend/api/MirrorOfErised/MirrorOfErised/appsettings.json:/app/appsettings.json:ro
      - ~/Pictures/Data:/app/Data
      - ~/Pictures/Data/train:/app/wwwroot/images/processed
      - ~/Documents/school/magic-mirror/facial_recognition.pth:/python/facial_recognition.pth
      - ./python/config.docker.json:/root/Documents/config.json
  api:
    container_name: api
    image: api:x86
    depends_on:
      - database
    expose:
      - "80"
    ports:
      - "5003:80"
    environment:
      Authentication:Google:ClientId: ${GOOGLE_CLIENT_ID}
      Authentication:Google:ClientSecret: ${GOOGLE_CLIENT_SECRET}
      Tokens:Key: MirrorMirrorOnTheWall
volumes:
  dbdata:
