version: "3.6"
services:
  database:
    container_name: postgres
    image: postgres:alpine
    expose:
      - "5432"
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - "dbdata:/var/lib/postgresql/data"
  webapp:
    container_name: webapp
    image: florianvd/mirror-of-erised:webapp-arm32
    depends_on:
      - database
    ports:
      - "80:80"
    environment:
      CONTAINERIZED: 'true'
      Authentication:Google:ClientId: ${GOOGLE_CLIENT_SECRET}
      Authentication:Google:ClientSecret: ${GOOGLE_CLIENT_SECRET}
  api:
    container_name: api
    image: florianvd/mirror-of-erised:api-arm32
    depends_on:
      - database
    expose:
      - "80"
    ports:
      - "5003:80"
    environment:
      Authentication:Google:ClientId: ${GOOGLE_CLIENT_SECRET}
      Authentication:Google:ClientSecret: ${GOOGLE_CLIENT_SECRET}
volumes:
  dbdata:
