# This is a basic workflow to help you get started with Actions

name: WebApp Build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
    types:
      - closed
    branches:
      - 'master'
  push:
    branches:
      - develop

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  webapp:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    name: Build ASP.NET webapp docker image for arm architecture
    steps:
    - uses: actions/checkout@v2
    - uses: crazy-max/ghaction-docker-buildx@v2
    - name: Cache Docker layers
      uses: actions/cache@v2
      id: cache
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-
    - name: Docker login
      env:
        DOCKERHUB_ACCESS_TOKEN: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
        DOCKERHUB_USER: florianvd
      run: |
        echo $DOCKERHUB_ACCESS_TOKEN | docker login --username $DOCKERHUB_USER --password-stdin
    - name: Run buildx
      if: success()
      run: |
        cd backend/api/MirrorOfErised
        docker buildx build --output "type=image,push=true" --platform linux/arm64 --file MirrorOfErised/Dockerfile --tag florianvd/mirror-of-erised:webapp-latest .
  
  api:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    name: Build ASP.NET api docker image for arm architecture
    steps:
    - uses: actions/checkout@v2
    - uses: crazy-max/ghaction-docker-buildx@v2
    - name: Cache Docker layers
      uses: actions/cache@v2
      id: cache
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-
    - name: Docker login
      env:
        DOCKERHUB_ACCESS_TOKEN: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
        DOCKERHUB_USER: florianvd
      run: |
        echo $DOCKERHUB_ACCESS_TOKEN | docker login --username $DOCKERHUB_USER --password-stdin
    - name: Run buildx
      if: success()
      run: |
        cd backend/api/MirrorOfErised
        docker buildx build --output "type=image,push=true" --platform linux/arm64 --file MirrorOfErised.api/Dockerfile --tag florianvd/mirror-of-erised:api-latest .